- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - debug:
        msg: "{{ group_names }}"
    - name: Create example config file
      copy:
        dest: /etc/example.conf
        content: |
          server={{ server }}
        owner: root
        group: root
        mode: 0644
    - name: Show content
      command:
        cmd: cat /etc/example.conf
      changed_when: false
